name: shll

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_shll:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install openai pytest pyperclip
    - name: Run integration tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PYTHONUNBUFFERED: "1"
      run: |
        pytest test.py